[package]
name = "starrlight"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "Effortlessly create Awesome List from your GitHub stars."
authors = ["Yehezkiel Dio Sinolungan <yehezkieldio@proton.me>"]
license = "MIT"
keywords = ["cli", "tool", "utility", "github", "stars", "awesome-list"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"
repository = "https://github.com/yehezkieldio/starrlight"
homepage = "https://github.com/yehezkieldio/starrlight"

[[bin]]
name = "starrlight"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.40", features = ["derive", "env"] }
dirs = "6.0.0"
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
# Caching dependencies
sha2 = "0.10.8"
chrono = { version = "0.4.38", features = ["serde"] }
fs4 = "0.8.4"
thiserror = "2.0.12"
