use clap::Parser;
use reqwest::header::{AUTHORIZATION, HeaderMap, HeaderValue, USER_AGENT};
use serde::Deserialize;
use serde_json::json;
use std::collections::BTreeMap;
use std::error::Error;
use std::fmt;
use tokio;

const VERSION: &str = "0.1.0";
const DEFAULT_CATEGORY: &str = "Others";
const TEXT_LENGTH_LIMIT: usize = 200;

const DESC: &str = r#"<!--lint disable awesome-contributing awesome-license awesome-list-item match-punctuation no-repeat-punctuation no-undefined-references awesome-spell-check-->
# Awesome Stars [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)

> A curated list of my GitHub stars! Generated by [starred](https://github.com/maguowei/starred).

## Contents
"#;

const LICENSE: &str = r#"
## License

[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [{username}](https://github.com/{username}) has waived all copyright and related or neighboring rights to this work.
"#;

#[derive(Debug)]
struct StarredError {
    message: String,
}

impl fmt::Display for StarredError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl Error for StarredError {}

impl From<reqwest::Error> for StarredError {
    fn from(err: reqwest::Error) -> Self {
        StarredError {
            message: format!("HTTP request error: {}", err),
        }
    }
}

impl From<serde_json::Error> for StarredError {
    fn from(err: serde_json::Error) -> Self {
        StarredError {
            message: format!("JSON parsing error: {}", err),
        }
    }
}

impl From<reqwest::Error> for Box<StarredError> {
    fn from(err: reqwest::Error) -> Self {
        Box::new(StarredError {
            message: format!("HTTP request error: {}", err),
        })
    }
}

impl From<serde_json::Error> for Box<StarredError> {
    fn from(err: serde_json::Error) -> Self {
        Box::new(StarredError {
            message: format!("JSON parsing error: {}", err),
        })
    }
}

#[derive(Parser)]
#[command(author, version = VERSION, about, long_about = None)]
struct Cli {
    /// GitHub username
    #[arg(long, env = "USER")]
    username: String,

    /// GitHub token
    #[arg(long, env = "GITHUB_TOKEN")]
    token: String,

    /// Sort by category[language/topic] name alphabetically
    #[arg(long, action = clap::ArgAction::SetTrue)]
    sort: bool,

    /// Category by topic, default is category by language
    #[arg(long, action = clap::ArgAction::SetTrue)]
    topic: bool,

    /// Topic stargazer_count gt number, set bigger to reduce topics number
    #[arg(long, default_value_t = 500)]
    topic_limit: i32,

    /// Repository name
    #[arg(long, default_value = "")]
    repository: String,

    /// File name
    #[arg(long, default_value = "README.md")]
    filename: String,

    /// Commit message
    #[arg(long, default_value = "update awesome-stars, created by starred")]
    message: String,

    /// Include private repos
    #[arg(long, action = clap::ArgAction::SetTrue)]
    private: bool,
}

#[derive(Debug, Clone)]
struct Repository {
    name: String,
    description: String,
    language: String,
    url: String,
    is_private: bool,
    topics: Vec<String>,
}

#[derive(Deserialize)]
struct GraphQLResponse {
    data: Data,
}

#[derive(Deserialize)]
struct Data {
    user: User,
}

#[derive(Deserialize)]
struct User {
    #[serde(rename = "starredRepositories")]
    starred_repositories: StarredRepositories,
}

#[derive(Deserialize)]
struct StarredRepositories {
    nodes: Vec<RepoNode>,
    #[serde(rename = "pageInfo")]
    page_info: PageInfo,
}

#[derive(Deserialize)]
struct RepoNode {
    #[serde(rename = "nameWithOwner")]
    name_with_owner: String,
    description: Option<String>,
    url: String,
    #[serde(rename = "isPrivate")]
    is_private: bool,
    languages: Languages,
    #[serde(rename = "repositoryTopics")]
    repository_topics: RepositoryTopics,
}

#[derive(Deserialize)]
struct Languages {
    edges: Vec<LanguageEdge>,
}

#[derive(Deserialize)]
struct LanguageEdge {
    node: LanguageNode,
}

#[derive(Deserialize)]
struct LanguageNode {
    name: String,
}

#[derive(Deserialize)]
struct RepositoryTopics {
    nodes: Vec<TopicNode>,
}

#[derive(Deserialize)]
struct TopicNode {
    topic: Topic,
}

#[derive(Deserialize)]
struct Topic {
    name: String,
    #[serde(rename = "stargazerCount")]
    stargazer_count: i32,
}

#[derive(Deserialize)]
struct PageInfo {
    #[serde(rename = "endCursor")]
    end_cursor: Option<String>,
    #[serde(rename = "hasNextPage")]
    has_next_page: bool,
}

struct GitHubGQL {
    client: reqwest::Client,
    api_url: String,
}

impl GitHubGQL {
    fn new(token: &str) -> Self {
        let mut headers = HeaderMap::new();
        headers.insert(
            AUTHORIZATION,
            HeaderValue::from_str(&format!("Bearer {}", token)).unwrap(),
        );
        headers.insert(USER_AGENT, HeaderValue::from_static("starred-rust/0.1.0"));

        let client = reqwest::Client::builder()
            .default_headers(headers)
            .build()
            .unwrap();

        GitHubGQL {
            client,
            api_url: "https://api.github.com/graphql".to_string(),
        }
    }

    async fn get_user_starred_by_username(
        &self,
        username: &str,
        after: Option<String>,
        topic_stargazer_count_limit: i32,
    ) -> Result<Vec<Repository>, Box<StarredError>> {
        let mut items = Vec::new();

        let query = r#"
            query ($username: String!, $after: String) {
                user(login: $username) {
                    starredRepositories(first: 100, after: $after, orderBy: {direction: DESC, field: STARRED_AT}) {
                        totalCount
                        nodes {
                            name
                            nameWithOwner
                            description
                            url
                            stargazerCount
                            forkCount
                            isPrivate
                            pushedAt
                            updatedAt
                            languages(first: 1, orderBy: {field: SIZE, direction: DESC}) {
                                edges {
                                    node {
                                        id
                                        name
                                    }
                                }
                            }
                            repositoryTopics(first: 100) {
                                nodes {
                                    topic {
                                        name
                                        stargazerCount
                                    }
                                }
                            }
                        }
                        pageInfo {
                            endCursor
                            hasNextPage
                        }
                    }
                }
            }
        "#;

        let variables = json!({
            "username": username,
            "after": after
        });

        let request_body = json!({
            "query": query,
            "variables": variables
        });

        let response = self
            .client
            .post(&self.api_url)
            .json(&request_body)
            .send()
            .await?;

        if !response.status().is_success() {
            return Err(Box::new(StarredError {
                message: format!("HTTP error: {}", response.status()),
            }));
        }

        let graphql_response: GraphQLResponse = response.json().await?;
        let starred_repos = &graphql_response.data.user.starred_repositories;

        for repo in &starred_repos.nodes {
            let name = repo.name_with_owner.clone();
            let description = repo.description.clone().unwrap_or_default();
            let language = repo
                .languages
                .edges
                .first()
                .map(|edge| edge.node.name.clone())
                .unwrap_or_default();
            let url = repo.url.clone();
            let is_private = repo.is_private;
            let topics: Vec<String> = repo
                .repository_topics
                .nodes
                .iter()
                .filter(|topic_node| topic_node.topic.stargazer_count > topic_stargazer_count_limit)
                .map(|topic_node| topic_node.topic.name.clone())
                .collect();

            items.push(Repository {
                name,
                description,
                language,
                url,
                is_private,
                topics,
            });
        }

        println!(
            "Fetched {} starred repositories for user: {}",
            starred_repos.nodes.len(),
            username
        );

        // Recursively fetch next page if available
        if starred_repos.page_info.has_next_page {
            let mut next_items: Vec<Repository> = Box::pin(self.get_user_starred_by_username(
                username,
                starred_repos.page_info.end_cursor.clone(),
                topic_stargazer_count_limit,
            ))
            .await?;
            items.append(&mut next_items);
        }

        Ok(items)
    }
}

fn html_escape(text: &str) -> String {
    text.replace('>', "&gt;").replace('<', "&lt;")
}

fn truncate_description(description: &str) -> String {
    let escaped = html_escape(description);
    let cleaned = escaped.replace('\n', "").trim().to_string();
    if cleaned.len() > TEXT_LENGTH_LIMIT {
        format!("{}...", &cleaned[..TEXT_LENGTH_LIMIT])
    } else {
        cleaned
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let cli = Cli::parse();

    let gh = GitHubGQL::new(&cli.token);

    println!("Fetching starred repositories for user: {}", cli.username);

    let stars = match gh
        .get_user_starred_by_username(&cli.username, None, cli.topic_limit)
        .await
    {
        Ok(stars) => stars,
        Err(e) => {
            eprintln!("Error: {}", e);
            return Err(e as Box<dyn Error>);
        }
    };

    println!("{}", DESC);

    let mut repo_dict: BTreeMap<String, Vec<(String, String, String)>> = BTreeMap::new();

    for star in stars {
        // Skip private repos if --private is not set
        if star.is_private && !cli.private {
            continue;
        }

        let description = if star.description.is_empty() {
            String::new()
        } else {
            truncate_description(&star.description)
        };

        if cli.topic {
            let categories = if star.topics.is_empty() {
                vec![DEFAULT_CATEGORY.to_lowercase()]
            } else {
                star.topics.clone()
            };

            for category in categories {
                repo_dict.entry(category).or_insert_with(Vec::new).push((
                    star.name.clone(),
                    star.url.clone(),
                    description.clone(),
                ));
            }
        } else {
            let category = if star.language.is_empty() {
                DEFAULT_CATEGORY.to_string()
            } else {
                star.language.clone()
            };

            repo_dict.entry(category).or_insert_with(Vec::new).push((
                star.name.clone(),
                star.url.clone(),
                description.clone(),
            ));
        }
    }

    // Print table of contents
    for category in repo_dict.keys() {
        let anchor = category.to_lowercase().replace(' ', "-");
        println!("- [{}](#{})", category, anchor);
    }
    println!();

    // Print repositories by category
    for (category, repos) in &repo_dict {
        println!("## {} \n", category.replace('#', "# #"));
        for (name, url, description) in repos {
            println!("- [{}]({}) - {}", name, url, description);
        }
        println!();
    }

    println!("{}", LICENSE.replace("{username}", &cli.username));

    // Note: Repository creation/update functionality would require additional
    // GitHub REST API calls and is omitted for brevity in this port
    if !cli.repository.is_empty() {
        println!(
            "Note: Repository creation/update functionality not implemented in this Rust port"
        );
    }

    Ok(())
}
