use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::cli::{Cli, OutputFormat};
use crate::models::Repository;

const DEFAULT_CATEGORY: &str = "Others";
const TEXT_LENGTH_LIMIT: usize = 200;

const DESC: &str = r#"<!--lint disable awesome-contributing awesome-license awesome-list-item match-punctuation no-repeat-punctuation no-undefined-references awesome-spell-check-->
# Awesome Stars [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)

> A curated list of my GitHub stars! Generated by [starrlight](https://github.com/yehezkieldio/starrlight).

## Contents
"#;

const LICENSE: &str = r#"
## License

[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [{username}](https://github.com/{username}) has waived all copyright and related or neighboring rights to this work.
"#;

const PAGINATION_HEADER: &str = r#"<!--lint disable awesome-contributing awesome-license awesome-list-item match-punctuation no-repeat-punctuation no-undefined-references awesome-spell-check-->
# Awesome Stars (Part {part}) [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)

> A curated list of my GitHub stars! Generated by [starrlight](https://github.com/yehezkieldio/starrlight).

"#;

fn html_escape(text: &str) -> String {
    text.replace('>', "&gt;").replace('<', "&lt;")
}

fn truncate_description(description: &str) -> String {
    let escaped = html_escape(description);
    let cleaned = escaped.replace('\n', "").trim().to_string();
    if cleaned.len() > TEXT_LENGTH_LIMIT {
        format!("{}...", &cleaned[..TEXT_LENGTH_LIMIT])
    } else {
        cleaned
    }
}

fn organize_repositories(stars: Vec<Repository>, cli: &Cli) -> BTreeMap<String, Vec<(String, String, String)>> {
    let mut repo_dict: BTreeMap<String, Vec<(String, String, String)>> = BTreeMap::new();

    for star in stars {
        // Skip private repos if --private is not set
        if star.is_private && !cli.private {
            continue;
        }

        let description = if star.description.is_empty() {
            String::new()
        } else {
            truncate_description(&star.description)
        };

        if cli.topic {
            let categories = if star.topics.is_empty() {
                vec![DEFAULT_CATEGORY.to_lowercase()]
            } else {
                star.topics.clone()
            };

            for category in categories {
                repo_dict.entry(category).or_default().push((
                    star.name.clone(),
                    star.url.clone(),
                    description.clone(),
                ));
            }
        } else {
            let category = if star.language.is_empty() {
                DEFAULT_CATEGORY.to_string()
            } else {
                star.language.clone()
            };

            repo_dict.entry(category).or_default().push((
                star.name.clone(),
                star.url.clone(),
                description.clone(),
            ));
        }
    }

    // Sort repositories within each category if requested
    if cli.sort {
        for repos in repo_dict.values_mut() {
            repos.sort_by(|a, b| a.0.cmp(&b.0));
        }
    }

    repo_dict
}

fn generate_table_of_contents(repo_dict: &BTreeMap<String, Vec<(String, String, String)>>) -> String {
    let mut toc = String::new();
    for category in repo_dict.keys() {
        let anchor = category.to_lowercase().replace(' ', "-").replace('#', "");
        toc.push_str(&format!("- [{category}](#{anchor})\n"));
    }
    toc.push('\n');
    toc
}

fn generate_category_content(category: &str, repos: &[(String, String, String)]) -> String {
    let mut content = String::new();
    content.push_str(&format!("## {} \n\n", category.replace('#', "# #")));

    for (name, url, description) in repos {
        content.push_str(&format!("- [{name}]({url}) - {description}\n"));
    }
    content.push('\n');
    content
}

fn output_to_console(repo_dict: BTreeMap<String, Vec<(String, String, String)>>, cli: &Cli) {
    println!("{DESC}");

    // Print table of contents
    print!("{}", generate_table_of_contents(&repo_dict));

    // Print repositories by category
    for (category, repos) in &repo_dict {
        print!("{}", generate_category_content(category, repos));
    }

    println!("{}", LICENSE.replace("{username}", &cli.username));

    // Note: Repository creation/update functionality would require additional
    // GitHub REST API calls and is omitted for brevity in this port
    if !cli.repository.is_empty() {
        println!(
            "Note: Repository creation/update functionality not implemented in this Rust port"
        );
    }
}

fn output_to_markdown(repo_dict: BTreeMap<String, Vec<(String, String, String)>>, cli: &Cli) -> Result<(), Box<dyn std::error::Error>> {
    // Create output directory if it doesn't exist
    fs::create_dir_all(&cli.output_dir)?;

    let max_file_size = cli.max_file_size_kb * 1024; // Convert KB to bytes
    let mut current_file_content = String::new();
    let mut current_file_size = 0;
    let mut file_number = 1;
    let mut files_created = Vec::new();

    // Start with the main header
    current_file_content.push_str(DESC);
    current_file_size += DESC.len();

    // Generate table of contents for all categories
    let toc = generate_table_of_contents(&repo_dict);

    // For the first file, add the full TOC
    current_file_content.push_str(&toc);
    current_file_size += toc.len();

    for (category, repos) in &repo_dict {
        let category_content = generate_category_content(category, repos);
        let category_size = category_content.len();

        // Check if adding this category would exceed the file size limit
        if current_file_size + category_size > max_file_size && !current_file_content.is_empty() {
            // Add license to current file
            let license_content = LICENSE.replace("{username}", &cli.username);
            current_file_content.push_str(&license_content);

            // Save current file
            let filename = if file_number == 1 {
                "README.md".to_string()
            } else {
                format!("README-part-{}.md", file_number)
            };
            let filepath = Path::new(&cli.output_dir).join(&filename);
            fs::write(&filepath, &current_file_content)?;
            files_created.push(filename);

            println!("Created: {}", filepath.display());

            // Start new file
            file_number += 1;
            current_file_content = PAGINATION_HEADER.replace("{part}", &file_number.to_string());
            // current_file_size = current_file_content.len();

            // Add navigation to other parts
            current_file_content.push_str("## Navigation\n\n");
            for (i, created_file) in files_created.iter().enumerate() {
                let part_num = if i == 0 { 1 } else { i + 1 };
                current_file_content.push_str(&format!("- [Part {}]({})\n", part_num, created_file));
            }
            current_file_content.push('\n');
            current_file_size = current_file_content.len();
        }

        current_file_content.push_str(&category_content);
        current_file_size += category_size;
    }

    // Save the last file
    if !current_file_content.is_empty() {
        let license_content = LICENSE.replace("{username}", &cli.username);
        current_file_content.push_str(&license_content);

        let filename = if file_number == 1 {
            "README.md".to_string()
        } else {
            format!("README-part-{}.md", file_number)
        };
        let filepath = Path::new(&cli.output_dir).join(&filename);
        fs::write(&filepath, &current_file_content)?;
        files_created.push(filename);

        println!("Created: {}", filepath.display());
    }

    // Create an index file if multiple files were created
    if files_created.len() > 1 {
        let mut index_content = format!(
            "# Awesome Stars Index\n\n> Generated by [starrlight](https://github.com/yehezkieldio/starrlight) for [{username}](https://github.com/{username})\n\n",
            username = cli.username
        );
        index_content.push_str("This awesome list has been split into multiple files due to size constraints:\n\n");

        for (i, filename) in files_created.iter().enumerate() {
            let part_num = i + 1;
            index_content.push_str(&format!("- [Part {}]({})\n", part_num, filename));
        }

        let index_path = Path::new(&cli.output_dir).join("index.md");
        fs::write(&index_path, &index_content)?;
        println!("Created index: {}", index_path.display());
    }

    println!("\n✅ Successfully generated {} markdown file(s) in '{}'", files_created.len(), cli.output_dir);
    Ok(())
}

pub fn generate_output(stars: Vec<Repository>, cli: &Cli) {
    let repo_dict = organize_repositories(stars, cli);

    match cli.output {
        OutputFormat::Console => {
            output_to_console(repo_dict, cli);
        }
        OutputFormat::Markdown => {
            if let Err(e) = output_to_markdown(repo_dict, cli) {
                eprintln!("Error generating markdown output: {}", e);
            }
        }
    }
}
