use std::collections::BTreeMap;

use crate::cli::Cli;
use crate::models::Repository;

const DEFAULT_CATEGORY: &str = "Others";
const TEXT_LENGTH_LIMIT: usize = 200;

const DESC: &str = r#"<!--lint disable awesome-contributing awesome-license awesome-list-item match-punctuation no-repeat-punctuation no-undefined-references awesome-spell-check-->
# Awesome Stars [![Awesome](https://awesome.re/badge.svg)](https://github.com/sindresorhus/awesome)

> A curated list of my GitHub stars! Generated by [starred](https://github.com/maguowei/starred).

## Contents
"#;

const LICENSE: &str = r#"
## License

[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [{username}](https://github.com/{username}) has waived all copyright and related or neighboring rights to this work.
"#;

fn html_escape(text: &str) -> String {
    text.replace('>', "&gt;").replace('<', "&lt;")
}

fn truncate_description(description: &str) -> String {
    let escaped = html_escape(description);
    let cleaned = escaped.replace('\n', "").trim().to_string();
    if cleaned.len() > TEXT_LENGTH_LIMIT {
        format!("{}...", &cleaned[..TEXT_LENGTH_LIMIT])
    } else {
        cleaned
    }
}

pub fn generate_output(stars: Vec<Repository>, cli: &Cli) {
    println!("{}", DESC);

    let mut repo_dict: BTreeMap<String, Vec<(String, String, String)>> = BTreeMap::new();

    for star in stars {
        // Skip private repos if --private is not set
        if star.is_private && !cli.private {
            continue;
        }

        let description = if star.description.is_empty() {
            String::new()
        } else {
            truncate_description(&star.description)
        };

        if cli.topic {
            let categories = if star.topics.is_empty() {
                vec![DEFAULT_CATEGORY.to_lowercase()]
            } else {
                star.topics.clone()
            };

            for category in categories {
                repo_dict.entry(category).or_insert_with(Vec::new).push((
                    star.name.clone(),
                    star.url.clone(),
                    description.clone(),
                ));
            }
        } else {
            let category = if star.language.is_empty() {
                DEFAULT_CATEGORY.to_string()
            } else {
                star.language.clone()
            };

            repo_dict.entry(category).or_insert_with(Vec::new).push((
                star.name.clone(),
                star.url.clone(),
                description.clone(),
            ));
        }
    }

    // Print table of contents
    for category in repo_dict.keys() {
        let anchor = category.to_lowercase().replace(' ', "-");
        println!("- [{}](#{})", category, anchor);
    }
    println!();

    // Print repositories by category
    for (category, repos) in &repo_dict {
        println!("## {} \n", category.replace('#', "# #"));
        for (name, url, description) in repos {
            println!("- [{}]({}) - {}", name, url, description);
        }
        println!();
    }

    println!("{}", LICENSE.replace("{username}", &cli.username));

    // Note: Repository creation/update functionality would require additional
    // GitHub REST API calls and is omitted for brevity in this port
    if !cli.repository.is_empty() {
        println!(
            "Note: Repository creation/update functionality not implemented in this Rust port"
        );
    }
}
